# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: eduardo.alves@polo.ufsc.br
AuthorName: Eduardo
Indentation: 4
JuliaMinVersion: '1.10'
License: MIT
PackageName: TestePacote
PackageOwner: Eduardo-BDMAlves
PackageUUID: f6c3ff5e-eeb9-56c6-8c25-15f415605710
_commit: v0.9.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
